### PR TITLE
Upgrade to ng4

### PR DESCRIPTION
**Pull request by akkumar**
Upgrade to ng4  ( +zone.js, typescript, tslint as necessary ) 

Convert prepublish to prepare - regarding scripts in package.json 

add lib option to tsconfig.

### CODE REVIEW

**Comment by brtnshrdr** [comment]
Thanks!

**Comment by Matmo10** [comment]
Any plans for a new release?

**Comment by brtnshrdr** [comment]
I’ll do the release sometime this week. I’m away for the weekend

**Comment by Matmo10** [comment]
Awesome, thanks!

**Pull request merged**
